version: '3'
services:
  kurento-server:
    container_name: kurento-server
    image: "kurento/kurento-media-server:trusty-latest"
    ports: 
    - "0.0.0.0:8888:8888"
  kurento-room:
    container_name: kurento-room
    image: "syq7970/kurento-room"
    ports: 
      - "0.0.0.0:8443:8443"
    links:
      - kurento-server:kms
  coturn-server:
    container_name: coturn-server
    image: "steppechange/docker-coturn"

